import Foundation

struct APIErrorResponse: Decodable {
    let error: APIErrorBody
}

struct APIErrorBody: Decodable {
    let code: String
    let message: String
}

struct SessionSummary: Codable {
    let signedIn: Bool
    let selectedAccountId: String?
}

struct AuthStartResponse: Codable {
    let status: String
    let signInCode: String
    let verificationUrl: String
    let verificationUrlComplete: String?
    let expiresInSec: Int
    let pollIntervalSec: Int
}

extension AuthStartResponse {
    var verificationURLWithCode: String {
        if let verificationUrlComplete, !verificationUrlComplete.isEmpty {
            return verificationUrlComplete
        }
        guard var components = URLComponents(string: verificationUrl) else {
            return verificationUrl
        }
        var items = components.queryItems ?? []
        if !items.contains(where: { $0.name == "user_code" }) {
            items.append(URLQueryItem(name: "user_code", value: signInCode))
        }
        components.queryItems = items
        return components.string ?? verificationUrl
    }
}

struct AuthPollResponse: Codable {
    let status: String
    let selectedAccountId: String?
}

struct StatusResponse: Codable {
    let status: String
}

struct AccountListResponse: Codable {
    let selectedAccountId: String?
    let accounts: [AccountSummary]
}

struct AccountSummary: Codable, Identifiable {
    let id: String
    let name: String
    let email: String?
    let avatarUrl: String?
    let selected: Bool
}

struct SelectAccountRequest: Codable {
    let accountId: String?
}

struct SelectAccountResponse: Codable {
    let selectedAccountId: String?
}

struct RemoveAccountRequest: Codable {
    let accountId: String
}

struct RefreshAccountsResponse: Codable {
    let status: String
    let selectedAccountId: String?
    let discoveredProfileCount: Int
    let totalProfileCount: Int
}

struct FeedResponse: Codable {
    let title: String
    let continuationToken: String?
    let items: [VideoFeedItem]
}

struct VideoFeedItem: Codable, Identifiable {
    let videoId: String
    let title: String
    let channelName: String
    let channelId: String
    let thumbnailUrl: String
    let publishedText: String
    let durationSec: Int

    var id: String { videoId }
}

struct VideoMetadataResponse: Codable {
    let videoId: String
    let title: String
    let channelName: String
    let channelId: String
    let publishedText: String
    let viewCountText: String
    let description: String
    let commentsKey: String?
    let liveChatKey: String?
}

struct PlaybackResponse: Codable {
    let videoId: String
    let streamUrl: String
    let mimeType: String
    let qualityLabel: String?
    let isAdaptive: Bool?
    let availableStreams: [PlaybackStreamOption]?
    let subtitleTracks: [SubtitleTrack]?
    let expiresAtEpochSec: Int
}

struct PlaybackStreamOption: Codable, Identifiable, Hashable {
    let id: String
    let streamUrl: String
    let mimeType: String
    let qualityLabel: String
    let isAdaptive: Bool
}

struct SubtitleTrack: Codable, Identifiable, Hashable {
    let id: String
    let language: String
    let label: String
    let url: String
    let isAutoGenerated: Bool
}

struct SearchSuggestionsResponse: Codable {
    let query: String
    let suggestions: [String]
}

struct CommentsResponse: Codable {
    let nextCommentsKey: String?
    let items: [CommentItem]
}

struct CommentItem: Codable, Identifiable {
    let id: String
    let authorName: String
    let authorPhotoUrl: String
    let publishedText: String
    let message: String
    let likeCountText: String
    let replyCountText: String
    let nestedCommentsKey: String?
}

struct WatchProgressEntry: Codable, Identifiable, Hashable {
    let accountId: String
    let videoId: String
    let title: String
    let channelName: String
    let thumbnailUrl: String
    let lastPositionSec: Double
    let durationSec: Double
    let updatedAtEpochSec: Int

    var id: String { "\(accountId)|\(videoId)" }

    var progressFraction: Double {
        guard durationSec > 0 else { return 0 }
        return min(max(lastPositionSec / durationSec, 0), 1)
    }
}
