#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROFILES_FILE="${ROOT_DIR}/.youtube_api_profiles.env"
ACTIVE_FILE="${ROOT_DIR}/.youtube_api_active.env"

usage() {
  cat <<'EOF'
Usage: scripts/switch-youtube-key.sh <1|2>

Switches the active YouTube API credentials profile and writes:
  .youtube_api_active.env
EOF
}

if [[ "${1:-}" =~ ^(-h|--help)$ ]]; then
  usage
  exit 0
fi

PROFILE="${1:-}"

if [[ -z "${PROFILE}" || ( "${PROFILE}" != "1" && "${PROFILE}" != "2" ) ]]; then
  usage >&2
  exit 1
fi

if [[ ! -f "${PROFILES_FILE}" ]]; then
  echo "Profiles file not found: ${PROFILES_FILE}" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "${PROFILES_FILE}"

api_key_var="YOUTUBE_API_KEY_${PROFILE}"
client_id_var="YOUTUBE_CLIENT_ID_${PROFILE}"
client_secret_var="YOUTUBE_CLIENT_SECRET_${PROFILE}"

api_key="${!api_key_var:-}"
client_id="${!client_id_var:-}"
client_secret="${!client_secret_var:-}"

if [[ -z "${api_key}" || -z "${client_id}" || -z "${client_secret}" ]]; then
  echo "Profile ${PROFILE} is incomplete in ${PROFILES_FILE}" >&2
  exit 1
fi

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

cat > "${ACTIVE_FILE}" <<EOF
# Auto-generated by scripts/switch-youtube-key.sh at ${timestamp}
YOUTUBE_API_KEY="${api_key}"
YOUTUBE_CLIENT_ID="${client_id}"
YOUTUBE_CLIENT_SECRET="${client_secret}"
YOUTUBE_ACTIVE_PROFILE="${PROFILE}"
EOF

chmod 600 "${ACTIVE_FILE}"

cat <<EOF
Switched to profile ${PROFILE}.
Active credentials file:
  ${ACTIVE_FILE}

To load in your shell:
  set -a; source "${ACTIVE_FILE}"; set +a
EOF
